# Generated by Django 5.1 on 2026-04-21 14:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('clearance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='approverprofile',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clearance.unit'),
        ),
        migrations.AddField(
            model_name='approverprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='approver_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
